Fixed fatal error when exception message is an object
Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in ../vendor/bigcommerce/api/src/Bigcommerce/Api/Error.php on line 18

BigCommerce 401 response {"error":"You are authorized but your scope does not include this resource."}